# Generated by Django 5.0 on 2023-12-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_alter_module_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order_number'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='module',
            name='order_number',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
            preserve_default=False,
        ),
    ]
